#Oracle connection2

datasrc.url=jdbc:oracle:thin:@122.165.217.18:1521/BRECON
datasrc.username=BRECON
datasrc.password=brecon  

#datasrc.url=jdbc:oracle:thin:@10.255.255.125:1521/UBSPDB
#datasrc.username=BORNFIRE
#datasrc.password=HAb4Fjbf0c3fhit

#datasrc.url=jdbc:oracle:thin:@localhost:1521/ORCL
#datasrc.username=BRECON
#datasrc.password=HAb4Fjbf0c3fhit


default.password=Bornfire@123
default.pagesize=15

#File output Path
output.exportpath=D:/
#Session
spring.session.store-type=jdbc
spring.session.timeout=1800

#Hibernate
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.properties.hibernate.current_session_context_class=org.springframework.orm.hibernate5.SpringSessionContext
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.open-in-view=false


#Server
server.servlet.context-path=/BRECON


#Security
spring.resources.add-mappings=true
#logging.level.org.springframework.security=DEBUG

#Logging
debug=false
#C:\MIS\ReportGeneration\Desktop\download\Modified_file_path

#File upload
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

#mail.host=webmail.bornfire.in
#mail.port=25
#mail.username=ramprasath.p@bornfire.in
#mail.password=Rambornfire

mail.host=webmail.bornfire.in
mail.port=25
mail.username=manivannan.b@bornfire.co.in
mail.password=Bornfire#123

spring.jpa.properties.hibernate.jdbc.batch_size=1000
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true


server.port=8099
#server.ssl.key-store=classpath:abc-cardsettlement-uat.abcbanking.local.jks
#server.ssl.key-store-password=Password123!!
#server.ssl.key-store-type=JKS
#server.ssl.key-alias=tomcat